title: "SPRING Doctoral Network"
description: "SPRING: Doctoral Network for resilience experts in future large-scale critical infrastructures."

# IMPORTANT for GitHub project pages:
url: "https://spring-dn.github.io"      # GitHub org/user root
baseurl: "/spring-website"              # repo name, with leading /

markdown: kramdown
theme: null
plugins: []