title: "SPRING Doctoral Network"
description: "MSCA Doctoral Network for resilience experts in future large-scale critical infrastructures."

# IMPORTANT for GitHub project pages:
url: "https://spring-project.eu"      # 
baseurl: "/"              # repo name, with leading /

markdown: kramdown
theme: null
plugins: []